spring.application.name=field_Investigation_system


spring.datasource.url=jdbc:mysql://localhost:3306/field_investigation_db
spring.datasource.username=chetan
spring.datasource.password=Chetan@902

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool (recommended)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

